spring:
  application:
    name: Jq_Server
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    primary:
      url: jdbc:postgresql://43.136.32.212:5432/bestfarmer
      username: postgres
      password: 7307913.5t5t
      driver-class-name: org.postgresql.Driver
    secondary:
      url: jdbc:postgresql://43.136.32.212:5432/apijson
      username: postgres
      password: 7307913.5t5t
      driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Shanghai
  data:
    redis:
      database: 0
      host: 10.0.0.1
      port: 6379
      lettuce:
        pool:
          max-idle: 10
          min-idle: 5
          max-active: 200
      timeout: 10000
server:
  port: 8089
  shutdown: graceful
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志 pro下关闭日志输出
  is-log: false
