spring:
  application:
    name: Jq_Server
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    primary:
      url: jdbc:postgresql://43.136.32.212:5432/bestfarmer
      username: postgres
      password: 7307913.5t5t
      driver-class-name: org.postgresql.Driver
    secondary:
      url: jdbc:postgresql://43.136.32.212:5432/apijson
      username: postgres
      password: 7307913.5t5t
      driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Shanghai
  data:
    redis:
      database: 0
      host: 10.0.0.1
      port: 6379
      lettuce:
        pool:
          max-idle: 10
          min-idle: 5
          max-active: 200
      timeout: 10000
  cache:
    type: redis
server:
  port: 80
  shutdown: graceful
Jwt:
  secret: aB3#xY7!qW9@zC1$vD5%fG6^hJ8&kL0*pO2(uQ4)rS6-tU8ppRQ
  expire: 3600000
  issuer: JqYy

